name: CI

on:
  push:
    branches: [ ci ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: update
        run: |
          ls
          cat class5.cpp
          g++ class5.cpp
          ./a.out >> temp.txt
          cat temp.txt
          cat temp.txt >> README.md
          rm -f temp.txt a.out
          echo "" >> README.md
          echo "抽取时间：" >> README.md
          date >> README.md
          echo "" >> README.md
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add -A
          git commit -m "[skip ci] Upload results, $(date)"
          git log
          git push https://bobby285271:${CODINGPASSWD}@github.com/bobby285271/stuselect.git ci --force


